// WordPress publish connector — uses the core REST API (WP 5.6+) with
// Application Passwords for HTTP Basic auth. No plugins required.
//
// Verified against developer.wordpress.org:
//   POST {site}/wp-json/wp/v2/posts
//   Auth: Authorization: Basic base64(username:application_password)
//   Body (write): { title, content, status, slug, excerpt } as plain strings.
//                 (The schema lists title/content as "object" but that's the
//                  read shape `{ rendered, raw }`. Writes accept strings —
//                  see the curl example in the REST authentication docs.)
//   Response: { link, ... } — `link` is the public URL.
//
// Application Passwords are generated by the WP user at
//   wp-admin → Users → Edit User → Application Passwords
// (separate from the user's login password; revocable independently).
import "server-only";

import type { Company } from "@/lib/supabase/types";
import {
  CmsNotConfiguredError,
  CmsPublishError,
  type BlogDraft,
  type PublishResult,
} from "./types";
import { markdownToBasicHtml } from "./markdown";

export async function publishPost(
  _company: Company,
  draft: BlogDraft,
): Promise<PublishResult> {
  const site = (process.env.WORDPRESS_SITE_URL || "").trim();
  const username = (process.env.WORDPRESS_USERNAME || "").trim();
  const appPassword = (process.env.WORDPRESS_APP_PASSWORD || "").trim();

  if (!site || !username || !appPassword) {
    throw new CmsNotConfiguredError(
      "Set WORDPRESS_SITE_URL, WORDPRESS_USERNAME, and WORDPRESS_APP_PASSWORD in .env.local. " +
        "Generate an Application Password at wp-admin → Users → Edit User → Application Passwords.",
    );
  }

  // Normalize: strip trailing slash; the REST path is appended verbatim.
  const base = site.replace(/\/+$/, "");
  const endpoint = `${base}/wp-json/wp/v2/posts`;
  // WP Application Passwords ignore spaces; users often paste them with the
  // 4-char chunks the admin UI displays. Strip whitespace defensively.
  const authToken = Buffer.from(`${username}:${appPassword.replace(/\s+/g, "")}`).toString(
    "base64",
  );

  const body = {
    title: draft.title,
    content: markdownToBasicHtml(draft.body_md),
    status: "publish" as const,
    slug: draft.slug ?? undefined,
    excerpt: draft.meta_description ?? undefined,
  };

  let res: Response;
  try {
    res = await fetch(endpoint, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Basic ${authToken}`,
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new CmsPublishError(
      `WordPress site unreachable at ${endpoint}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    // WP returns helpful JSON errors like {"code":"rest_cannot_create","message":"..."}.
    // Surface them directly so the user sees exactly what's wrong (wrong creds,
    // user lacks publish capability, etc).
    let detail = text.slice(0, 400);
    try {
      const j = JSON.parse(text) as { code?: string; message?: string };
      if (j.message) detail = `${j.code ?? "error"}: ${j.message}`;
    } catch {
      /* keep raw text */
    }
    throw new CmsPublishError(
      `WordPress ${res.status} on POST /wp-json/wp/v2/posts — ${detail}`,
      res.status,
    );
  }

  const j = (await res.json().catch(() => ({}))) as { link?: string; id?: number };
  if (!j.link) {
    throw new CmsPublishError(
      "WordPress returned 2xx but no `link` field on the response; can't surface a public URL.",
    );
  }
  return { url: j.link };
}
